package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.26

import (
	"context"
	"fmt"

	"github.com/humgal/art-server/graph/model"
)

// PlaceBid is the resolver for the placeBid field.
func (r *mutationResolver) PlaceBid(ctx context.Context, bid *model.BidParm) (*model.Bid, error) {
	panic(fmt.Errorf("not implemented: PlaceBid - placeBid"))
}

// UploadArt is the resolver for the uploadArt field.
func (r *mutationResolver) UploadArt(ctx context.Context, items []*model.UploadItem) ([]*model.Item, error) {
	panic(fmt.Errorf("not implemented: UploadArt - uploadArt"))
}

// SetPrice is the resolver for the setPrice field.
func (r *mutationResolver) SetPrice(ctx context.Context, param *model.PriceParam) ([]*model.Item, error) {
	panic(fmt.Errorf("not implemented: SetPrice - setPrice"))
}

// MintArt is the resolver for the mintArt field.
func (r *mutationResolver) MintArt(ctx context.Context, items []string) ([]*model.Item, error) {
	panic(fmt.Errorf("not implemented: MintArt - mintArt"))
}

// CreateCollection is the resolver for the createCollection field.
func (r *mutationResolver) CreateCollection(ctx context.Context, param model.CollectionParm) (*model.Collection, error) {
	panic(fmt.Errorf("not implemented: CreateCollection - createCollection"))
}

// Checkout is the resolver for the checkout field.
func (r *mutationResolver) Checkout(ctx context.Context, param *model.PayParam) (*string, error) {
	panic(fmt.Errorf("not implemented: Checkout - checkout"))
}

// ConnectWallet is the resolver for the connectWallet field.
func (r *mutationResolver) ConnectWallet(ctx context.Context, userID string, typeArg model.WalletType) (*model.Wallet, error) {
	panic(fmt.Errorf("not implemented: ConnectWallet - connectWallet"))
}

// SearchItems is the resolver for the searchItems field.
func (r *queryResolver) SearchItems(ctx context.Context, param model.SearchParm) ([]*model.Item, error) {
	panic(fmt.Errorf("not implemented: SearchItems - searchItems"))
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Item is the resolver for the item field.
func (r *queryResolver) Item(ctx context.Context, id string) (*model.Item, error) {
	panic(fmt.Errorf("not implemented: Item - item"))
}

// Collection is the resolver for the collection field.
func (r *queryResolver) Collection(ctx context.Context, createor string) (*model.Collection, error) {
	panic(fmt.Errorf("not implemented: Collection - collection"))
}

// Items is the resolver for the items field.
func (r *queryResolver) Items(ctx context.Context, createor *string, ids []string) ([]*model.Item, error) {
	panic(fmt.Errorf("not implemented: Items - items"))
}

// Createor is the resolver for the createor field.
func (r *queryResolver) Createor(ctx context.Context, name *string) (*model.Creator, error) {
	panic(fmt.Errorf("not implemented: Createor - createor"))
}

// FeatureCreator is the resolver for the featureCreator field.
func (r *queryResolver) FeatureCreator(ctx context.Context, typeArg int) ([]*model.Creator, error) {
	panic(fmt.Errorf("not implemented: FeatureCreator - featureCreator"))
}

// SubscriptionPayment is the resolver for the subscriptionPayment field.
func (r *subscriptionResolver) SubscriptionPayment(ctx context.Context, itemid *string) (<-chan []*model.Payment, error) {
	panic(fmt.Errorf("not implemented: SubscriptionPayment - subscriptionPayment"))
}

// SubscriptionBid is the resolver for the subscriptionBid field.
func (r *subscriptionResolver) SubscriptionBid(ctx context.Context, itemid *string) (<-chan []*model.Bid, error) {
	panic(fmt.Errorf("not implemented: SubscriptionBid - subscriptionBid"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
